### ISSUE TITLE
Не запускается!

### ISSUE THREAD

**Issue by evtn** [maxi-team/precoil#1]
Не запускается!!!!!!!!!

Ошибка: mta_sa.exe has stopped working

Помогите!

Если не поможете поставлю одну звезду

**Comment by eolme** [comment]
Не относится к данной библиотеке. Попробуйте поискать решение в интернете.

**Comment by evtn** [comment]
Спасибо, помогло.

**Comment by worldwidebaby** [comment]
стоп мне не помогло

**Comment by worldwidebaby** [comment]
@evtn  вы как проблему решили

**Comment by evtn** [comment]
> @evtn  вы как проблему решили
> 

я сделал все как сказал @eolme и мне помогло

**Comment by worldwidebaby** [comment]
> > @evtn  вы как проблему решили
> 
> я сделал все как сказал @eolme и мне помогло

мне не помогло может стоит еще раз попросить @eolme  помощи

**Comment by land47** [comment]
**я** вот **д**умаю @**e**olme **б**удет **ил**и не будет помогать

**Comment by evtn** [comment]
> **я** вот **д**умаю @**e**olme **б**удет **ил**и не будет помогать

# если *попросить* @eolme то он наверное поможет

**Comment by land47** [comment]
@eolme  что за дела я не понимаю подключил ваш скрипт а на странице это всплывает
![rAg-IwdRWHI](https://user-images.githubusercontent.com/53087814/106376461-a17d5a80-63a6-11eb-9205-167ec86d8b54.jpg)
